---
id: Text_Filter_Jsmin
name: Text_Filter_Jsmin
full: |-
  Text filtering and conversion library - JSMin driver
description: >-
  The JSMin javascript minifier driver for use with the Horde_Text_Filter
  library.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 1.0.3
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: JSMin
  uri:
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Text_Filter: ^2.2
